package ru.quipy.api.task

const val CREATED_TASK_EVENT = "CREATE_TASK_EVENT"
const val REMOVED_TASK_EVENT = "REMOVE_TASK_EVENT"
const val ASSIGNED_TASK_EVENT = "ASSIGNEE_TASK_EVENT"
const val UPDATED_TASK_NAME_EVENT = "UPDATE_TASK_NAME_EVENT"
const val UPDATED_TASK_DESCRIPTION_EVENT = "UPDATE_TASK_DESCRIPTION_EVENT"
const val UPDATED_TASK_STATUS_EVENT = "UPDATE_TASK_STATUS_EVENT"
